export { default as Banner } from './Banner';
export { default as BannerLanding } from './BannerLanding';
export { default as Contact } from './Contact';
export { default as Footer } from './Footer';
export { default as Header } from './Header';
export { default as Icon } from './Icon';
export { default as Layout } from './Layout';
export { default as Menu } from './Menu';
export { default as Tile } from './Tile';
